"""base_inicial_final

Revision ID: 604dbfb2b0a5
Revises: 
Create Date: 2025-11-25 15:27:07.556506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '604dbfb2b0a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ca_keyword',
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('puntos_nombre', sa.Integer(), nullable=False),
    sa.Column('puntos_descripcion', sa.Integer(), nullable=False),
    sa.Column('puntos_productos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('keyword_id')
    )
    op.create_index(op.f('ix_ca_keyword_keyword'), 'ca_keyword', ['keyword'], unique=True)
    op.create_table('ca_sector',
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('sector_id')
    )
    op.create_index(op.f('ix_ca_sector_nombre'), 'ca_sector', ['nombre'], unique=True)
    op.create_table('ca_organismo',
    sa.Column('organismo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=1000), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['ca_sector.sector_id'], ),
    sa.PrimaryKeyConstraint('organismo_id')
    )
    op.create_index(op.f('ix_ca_organismo_nombre'), 'ca_organismo', ['nombre'], unique=True)
    op.create_table('ca_licitacion',
    sa.Column('ca_id', sa.Integer(), nullable=False),
    sa.Column('codigo_ca', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=1000), nullable=True),
    sa.Column('monto_clp', sa.Float(), nullable=True),
    sa.Column('fecha_publicacion', sa.Date(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_cierre_segundo_llamado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado_ca_texto', sa.String(length=255), nullable=True),
    sa.Column('estado_convocatoria', sa.Integer(), nullable=True),
    sa.Column('proveedores_cotizando', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('direccion_entrega', sa.String(length=1000), nullable=True),
    sa.Column('plazo_entrega', sa.Integer(), nullable=True),
    sa.Column('productos_solicitados', sa.JSON(), nullable=True),
    sa.Column('puntaje_detalle', sa.JSON(), nullable=True),
    sa.Column('puntuacion_final', sa.Integer(), nullable=False),
    sa.Column('organismo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organismo_id'], ['ca_organismo.organismo_id'], ),
    sa.PrimaryKeyConstraint('ca_id')
    )
    op.create_index(op.f('ix_ca_licitacion_codigo_ca'), 'ca_licitacion', ['codigo_ca'], unique=True)
    op.create_index(op.f('ix_ca_licitacion_puntuacion_final'), 'ca_licitacion', ['puntuacion_final'], unique=False)
    op.create_table('ca_organismo_regla',
    sa.Column('regla_id', sa.Integer(), nullable=False),
    sa.Column('organismo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('PRIORITARIO', 'NO_DESEADO', name='tipo_regla_organismo_enum', native_enum=False), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organismo_id'], ['ca_organismo.organismo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('regla_id')
    )
    op.create_index(op.f('ix_ca_organismo_regla_organismo_id'), 'ca_organismo_regla', ['organismo_id'], unique=True)
    op.create_index(op.f('ix_ca_organismo_regla_tipo'), 'ca_organismo_regla', ['tipo'], unique=False)
    op.create_table('ca_seguimiento',
    sa.Column('ca_id', sa.Integer(), nullable=False),
    sa.Column('es_favorito', sa.Boolean(), nullable=False),
    sa.Column('es_ofertada', sa.Boolean(), nullable=False),
    sa.Column('es_oculta', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ca_id'], ['ca_licitacion.ca_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ca_id')
    )
    op.create_index(op.f('ix_ca_seguimiento_es_favorito'), 'ca_seguimiento', ['es_favorito'], unique=False)
    op.create_index(op.f('ix_ca_seguimiento_es_oculta'), 'ca_seguimiento', ['es_oculta'], unique=False)
    op.create_index(op.f('ix_ca_seguimiento_es_ofertada'), 'ca_seguimiento', ['es_ofertada'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ca_seguimiento_es_ofertada'), table_name='ca_seguimiento')
    op.drop_index(op.f('ix_ca_seguimiento_es_oculta'), table_name='ca_seguimiento')
    op.drop_index(op.f('ix_ca_seguimiento_es_favorito'), table_name='ca_seguimiento')
    op.drop_table('ca_seguimiento')
    op.drop_index(op.f('ix_ca_organismo_regla_tipo'), table_name='ca_organismo_regla')
    op.drop_index(op.f('ix_ca_organismo_regla_organismo_id'), table_name='ca_organismo_regla')
    op.drop_table('ca_organismo_regla')
    op.drop_index(op.f('ix_ca_licitacion_puntuacion_final'), table_name='ca_licitacion')
    op.drop_index(op.f('ix_ca_licitacion_codigo_ca'), table_name='ca_licitacion')
    op.drop_table('ca_licitacion')
    op.drop_index(op.f('ix_ca_organismo_nombre'), table_name='ca_organismo')
    op.drop_table('ca_organismo')
    op.drop_index(op.f('ix_ca_sector_nombre'), table_name='ca_sector')
    op.drop_table('ca_sector')
    op.drop_index(op.f('ix_ca_keyword_keyword'), table_name='ca_keyword')
    op.drop_table('ca_keyword')
    # ### end Alembic commands ###
