"""add_category_to_keywords

Revision ID: aaa28eab2949
Revises: dc789a2b107e
Create Date: 2026-01-12 13:17:45.374705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa28eab2949'
down_revision: Union[str, Sequence[str], None] = 'dc789a2b107e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ca_keyword', sa.Column('categoria', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_ca_keyword_categoria'), 'ca_keyword', ['categoria'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ca_keyword_categoria'), table_name='ca_keyword')
    op.drop_column('ca_keyword', 'categoria')
    # ### end Alembic commands ###
