"""agregar columna es_nuevo a organismos

Revision ID: dc789a2b107e
Revises: 604dbfb2b0a5
Create Date: 2025-12-01 21:07:48.881515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc789a2b107e'
down_revision: Union[str, Sequence[str], None] = '604dbfb2b0a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ca_organismo', sa.Column('es_nuevo', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ca_organismo', 'es_nuevo')
    # ### end Alembic commands ###
